########################
# set local data and output folders
########################


base_folder: ""
tracking_data: {"siCdc42": ["siCDC42/SUM_230330_siCDC42_20dyn_TrackMate.csv"],
		"siScr": ["siScr/SUM_230413_siScr_TrackMate.csv"]}
