########################
# set local data and output folders
########################

base_folder: ""

output_folder: "../data/"


########################
# assign condtions to tracking data
########################

key_file: ""

condition_order: []

data_exclude: []

# quality control parameters

min_track_length: 12 # minimum track length in frames

# plot parameters

## bootstrap trajectory plots

observation_time: [0, 24]
number_of_tracks_per_file: 100 
number_of_tracks_per_condition: 300

# parameters for velocity computation

time_lag: 12 # interval for velocity computation in frames
single_time_point_evaluation: 48 

#remove these parameters
start_phase_2: 24 # start of phase 2 in frames 
end_phase_1: 48 # end of phase 1 in frames 


#parameters to save storage
decimal_places : 3